[[CUDA_Driver]]
arch = "x86_64"
git-tree-sha1 = "7a7fd08bbad6b42e7ed42fd2fc058e42039b075f"
lazy = true
libc = "glibc"
os = "linux"

    [[CUDA_Driver.download]]
    sha256 = "7866667028b5945bee04d8b6395cc9dc83c8850c01dd6f72d1301328c68b0cc5"
    url = "https://github.com/maleadt/CUDA_Driver_jll.jl/releases/download/CUDA_Driver-v0.5.0+2/CUDA_Driver.v0.5.0.x86_64-linux-gnu.tar.gz"
