[[CUDA_Driver]]
arch = "x86_64"
git-tree-sha1 = "dbdabf2a4d62eda481e29d6d6e7033218f811aa8"
lazy = true
libc = "glibc"
os = "linux"

    [[CUDA_Driver.download]]
    sha256 = "0f0377317af341c54567cb10ea3341ba02964d6e8933e2f6d512bbf3577cd7c0"
    url = "https://github.com/maleadt/CUDA_Driver_jll.jl/releases/download/CUDA_Driver-v0.6.0+1/CUDA_Driver.v0.6.0.x86_64-linux-gnu.tar.gz"
